#!/usr/bin/env python3
"""Collate extraction records into a chronological ledger (Stage 2).

Ordering is by composition or delivery date, taken from
synthesis/chronology.json - never by volume number. Where a commentary
dates its own strata, units are grouped under the stratum they belong
to, so Ideas II appears as five layers between 1912 and 1928 rather than
as one entry.

The ledger narrates nothing. It orders, groups, and prints absences
beside presences. Smoothing the sequence into a development is Stage 4's
job, and Stage 4 is required to do it against locators.

Every ledger ends with what it does not cover: commentaries where the
theme's terms occur but no extraction pass has run. Without that list a
reader cannot tell textual absence from an unread file - which is the
difference between a finding and an artifact of the queue.

    python3 scripts/synthesis_ledger.py --theme sorge
    python3 scripts/synthesis_ledger.py --all
    python3 scripts/synthesis_ledger.py --all --check

Output is a pure function of the records: no timestamps, so a rebuild
that changes nothing produces no diff.
"""

import argparse
import os
import sys

import synthesislib as lib

HEADER = ("*Generated by `scripts/synthesis_ledger.py` from "
          "`synthesis/extractions/%s/`. Do not edit by hand - edit the "
          "extraction records and rebuild.*")


def unit_block(unit, doc, sections):
    sec = sections.get(unit["locator"].partition("#")[2])
    bits = ["- **%s** · `%s` · *%s*" % (unit["status"], unit["id"], unit["term"])]
    bits.append("  %s" % unit["claim"])
    trail = ["`%s`" % unit["locator"]]
    if unit.get("primary_locator"):
        trail.append(unit["primary_locator"])
    if sec:
        trail.append("[%s](%s)" % (" > ".join(sec["path"][-1:]),
                                   lib.section_url(doc, sec)))
    bits.append("  %s" % " · ".join(trail))
    bits.append("  > %s" % unit["quote"].replace("\n", " "))
    return "\n".join(bits)


def absence_block(absence, doc, sections):
    sec = sections.get(absence["locator"].partition("#")[2])
    bits = ["- **absent** · `%s`" % absence["locator"]]
    bits.append("  Expected because: %s" % absence["expected_because"])
    if absence.get("note"):
        bits.append("  %s" % absence["note"])
    if sec:
        bits.append("  [%s](%s)" % (" > ".join(sec["path"][-1:]),
                                    lib.section_url(doc, sec)))
    return "\n".join(bits)


def year_label(entry):
    years = []
    for s in entry["strata"]:
        if s["year_start"] is None:
            continue
        years.append(s["year_start"] if s["year_start"] == (s.get("year_end") or s["year_start"])
                     else "%d-%d" % (s["year_start"], s["year_end"]))
    if not years:
        return "undated"
    first, last = years[0], years[-1]
    return str(first) if first == last else "%s to %s" % (first, last)


def render_work(rec, entry, doc, out):
    sections = lib.section_map(doc)
    by_stratum = {}
    for unit in rec["units"]:
        by_stratum.setdefault(unit.get("stratum"), []).append(unit)

    order = [s["id"] for s in sorted(entry["strata"], key=lib.stratum_year)]
    keys = [k for k in order if k in by_stratum]
    if None in by_stratum:
        keys.append(None)

    for key in keys:
        if key is not None and len(entry["strata"]) > 1:
            out.append("#### %s" % lib.stratum_label(entry, key))
            out.append("")
        elif key is None and len(keys) > 1:
            out.append("#### Stratum not assigned by the commentary")
            out.append("")
        for unit in by_stratum[key]:
            out.append(unit_block(unit, doc, sections))
            out.append("")

    if rec["absences"]:
        out.append("#### Recorded absences")
        out.append("")
        for absence in rec["absences"]:
            out.append(absence_block(absence, doc, sections))
            out.append("")

    if rec["coverage"] == "partial":
        out.append("*Partial pass: %s*"
                   % rec.get("coverage_note", "scope not stated"))
        out.append("")


def build(theme, registry, corpus):
    cmap = lib.corpus_map(corpus)
    chron = lib.chronology()
    records = {rec["commentary"]: rec for _, rec in lib.load_extractions(theme)}

    groups = {"primary": [], "reception": [], "undated": []}
    for slug, rec in records.items():
        entry = chron.get(slug)
        if entry is None or entry["role"] == "output":
            continue
        bucket = ("undated" if entry["status"] == "unresolved"
                  else "reception" if entry["role"] == "reception" else "primary")
        groups[bucket].append((lib.entry_year(entry), slug, rec, entry))
    for bucket in groups.values():
        bucket.sort(key=lambda r: (r[0], r[1]))

    meta = registry[theme]
    out = ["# %s (%s) - chronological ledger" % (theme.capitalize(), meta["english"]),
           "", HEADER % theme, ""]
    if meta.get("note"):
        out += ["*%s*" % meta["note"], ""]

    units = sum(len(r["units"]) for r in records.values())
    absences = sum(len(r["absences"]) for r in records.values())
    out += ["%d units and %d recorded absences from %d commentaries."
            % (units, absences, len(records)), ""]

    titles = {"primary": "Primary corpus, by composition or delivery date",
              "reception": "Reception layer",
              "undated": "Undated - chronology unresolved"}
    notes = {
        "reception": "Read alongside the spine, not on it. A commentator's "
                     "date orders the reception, not the doctrine.",
        "undated": "These commentaries do not state a date for their text. "
                   "They are held out of the sequence rather than placed on a "
                   "guess; see `synthesis/chronology.json`.",
    }

    for bucket in ("primary", "reception", "undated"):
        if not groups[bucket]:
            continue
        out += ["## %s" % titles[bucket], ""]
        if bucket in notes:
            out += ["*%s*" % notes[bucket], ""]
        for _, slug, rec, entry in groups[bucket]:
            doc = cmap[slug]
            out += ["### %s - %s" % (year_label(entry), doc["title"]), "",
                    "`%s`" % slug, ""]
            render_work(rec, entry, doc, out)

    out += ["## Not covered by this ledger", "",
            "*Where the theme's terms occur but no extraction pass has run. "
            "Silence in the sections above is silence about these files, not "
            "evidence of absence in them.*", ""]

    terms = meta["search_terms"]
    uncovered = []
    for doc in corpus["documents"]:
        if doc["slug"] in records:
            continue
        entry = chron.get(doc["slug"])
        if entry and entry["role"] == "output":
            continue
        hits = lib.count_terms(lib.normalized_document(doc), terms)
        if hits:
            uncovered.append((hits, doc["slug"]))
    uncovered.sort(key=lambda r: (-r[0], r[1]))
    for hits, slug in uncovered:
        out.append("- `%s` - %d term hit%s, no record"
                   % (slug, hits, "" if hits == 1 else "s"))
    if not uncovered:
        out.append("- none: every commentary carrying the terms has a record")
    out.append("")
    return "\n".join(out)


def main(argv):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--theme")
    p.add_argument("--all", action="store_true")
    p.add_argument("--check", action="store_true",
                   help="exit 1 if a committed ledger is out of date")
    args = p.parse_args(argv[1:])

    registry = lib.themes()
    if args.all:
        themes = sorted({rec["theme"] for _, rec in lib.load_extractions()})
    elif args.theme:
        themes = [args.theme]
    else:
        p.error("give --theme or --all")

    stale = 0
    for theme in themes:
        if theme not in registry:
            print("unknown theme %r" % theme)
            return 2
        text = build(theme, registry, lib.load_corpus())
        path = os.path.join(lib.LEDGERS_DIR, "%s-ledger.md" % theme)
        rel = os.path.relpath(path, lib.REPO_ROOT).replace(os.sep, "/")
        if args.check:
            current = lib.read_text(path) if os.path.exists(path) else None
            if current != text:
                print("%s is out of date" % rel)
                stale += 1
            continue
        lib.write_text(path, text)
        print("wrote %s" % rel)

    if args.check:
        if stale:
            print("run python3 scripts/synthesis_ledger.py --all")
            return 1
        print("ledgers are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
