#!/usr/bin/env python3
"""Regenerate synthesis/STATUS.md - the queue for the next pass.

The pipeline is only worth building if it tells you what to do next.
This is that report: what has been extracted, what has gone stale under
an edited commentary, which commentaries carry a theme but have never
been scanned, which dates are still unresolved, and which gaps the last
synthesis pass flagged.

    python3 scripts/synthesis_status.py [--check]

Like the ledgers, the output carries no timestamp, so an unchanged
corpus rebuilds to an unchanged file.
"""

import argparse
import os
import sys

import synthesislib as lib

STATUS_PATH = os.path.join(lib.SYNTHESIS_DIR, "STATUS.md")
CANDIDATES = 6


def theme_section(theme, meta, corpus, chron, out):
    records = {rec["commentary"]: (rel, rec)
               for rel, rec in lib.load_extractions(theme)}
    cmap = lib.corpus_map(corpus)

    units = sum(len(r["units"]) for _, r in records.values())
    absences = sum(len(r["absences"]) for _, r in records.values())
    stale = [slug for slug, (_, r) in records.items()
             if cmap[slug]["sha256"] != r["source_sha256"]]
    partial = [slug for slug, (_, r) in records.items() if r["coverage"] == "partial"]

    out.append("### %s - %s" % (theme, meta["english"]))
    out.append("")
    out.append("%d commentar%s extracted · %d units · %d absences%s%s"
               % (len(records), "y" if len(records) == 1 else "ies",
                  units, absences,
                  " · %d stale" % len(stale) if stale else "",
                  " · %d partial" % len(partial) if partial else ""))
    out.append("")

    scored = []
    for doc in corpus["documents"]:
        entry = chron.get(doc["slug"])
        if entry and entry["role"] == "output":
            continue
        if doc["slug"] in records:
            continue
        hits = lib.count_terms(lib.normalized_document(doc), meta["search_terms"])
        if hits:
            scored.append((hits, doc["slug"], lib.entry_year(entry) if entry else lib.UNDATED))
    scored.sort(key=lambda r: -r[0])

    if scored:
        out.append("Next candidates, by term density:")
        out.append("")
        for hits, slug, year in scored[:CANDIDATES]:
            when = "undated" if year == lib.UNDATED else str(year)
            out.append("- [ ] `%s` (%s) - %d hits" % (slug, when, hits))
        if len(scored) > CANDIDATES:
            out.append("- ... %d more; see `synthesis_query.py --theme %s`"
                       % (len(scored) - CANDIDATES, theme))
        out.append("")
    elif records:
        out.append("Every commentary carrying these terms has a record.")
        out.append("")
    return stale


def main(argv):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true")
    args = p.parse_args(argv[1:])

    corpus = lib.load_corpus()
    chron = lib.chronology()
    registry = lib.themes()

    docs = corpus["documents"]
    out = ["# Synthesis status", "",
           "*Generated by `scripts/synthesis_status.py`. Do not edit by hand.*", "",
           "Corpus: **%d commentaries**, %s words, %d sections indexed in "
           "`synthesis/corpus.json`."
           % (len(docs), format(sum(d["words"] for d in docs), ","),
              sum(len(d["sections"]) for d in docs)),
           ""]

    out += ["## Themes", ""]
    all_stale = []
    for theme in sorted(registry):
        all_stale += [(theme, slug) for slug in
                      theme_section(theme, registry[theme], corpus, chron, out)]

    inh = lib.load_inheritance()
    cmap = lib.corpus_map(corpus)
    out += ["## Inheritance index", ""]
    if inh:
        out.append("%d commentar%s · %d engagements"
                   % (len(inh), "y" if len(inh) == 1 else "ies",
                      sum(len(r["engagements"]) for _, r in inh)))
        out.append("")
        for rel, rec in inh:
            marks = []
            if cmap[rec["commentary"]]["sha256"] != rec["source_sha256"]:
                marks.append("stale")
            if rec["coverage"] == "partial":
                marks.append("partial")
            out.append("- `%s` - %d engagements%s"
                       % (rec["commentary"], len(rec["engagements"]),
                          " (%s)" % ", ".join(marks) if marks else ""))
        out.append("")
    else:
        out += ["No inheritance records yet. Stage 3 is a separate pass over the "
                "same commentaries; see `prompts/inheritance-prompt.md`.", ""]

    if all_stale:
        out += ["## Stale records", "",
                "The commentary changed after the pass ran. Quotes are no longer "
                "guaranteed; re-extract and update `source_sha256`.", ""]
        for theme, slug in all_stale:
            out.append("- [ ] `synthesis/extractions/%s/%s.json`" % (theme, slug))
        out.append("")

    unresolved = [e for e in chron.values() if e["status"] == "unresolved"
                  and e["role"] != "output"]
    out += ["## Chronology to resolve", ""]
    if unresolved:
        out += ["These commentaries do not date their own text, so they sit off "
                "the ledger spine. Each is a reading task, not a lookup: the date "
                "belongs in the commentary first.", ""]
        for e in sorted(unresolved, key=lambda e: e["commentary"]):
            out.append("- [ ] `%s`%s" % (e["commentary"],
                                         " - " + e["note"] if e.get("note") else ""))
        out.append("")
    else:
        out += ["Every commentary states a date for its text.", ""]

    gaps = (lib.registry("gaps") or {"gaps": []})["gaps"]
    open_gaps = [g for g in gaps if g["status"] != "closed"]
    out += ["## Open gaps", ""]
    if open_gaps:
        out += ["Flagged by a synthesis pass as unsupported by the ledgers. This "
                "is the reading queue.", ""]
        for g in sorted(open_gaps, key=lambda g: g["id"]):
            out.append("- [ ] **%s** (%s%s) %s"
                       % (g["id"], g["status"],
                          ", " + g["theme"] if g.get("theme") else "", g["question"]))
            out.append("      *Needs:* %s" % g["needs"])
        out.append("")
    else:
        out += ["None recorded. A synthesis pass that flags no gaps has either "
                "exhausted its question or failed to look.", ""]

    text = "\n".join(out)
    rel = os.path.relpath(STATUS_PATH, lib.REPO_ROOT).replace(os.sep, "/")
    if args.check:
        current = lib.read_text(STATUS_PATH) if os.path.exists(STATUS_PATH) else None
        if current != text:
            print("%s is out of date - run python3 scripts/synthesis_status.py" % rel)
            return 1
        print("%s is up to date" % rel)
        return 0

    lib.write_text(STATUS_PATH, text)
    print("wrote %s" % rel)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
